language: python
python:
  - 3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda install -y conda=4.3.16
  - conda config --set show_channel_urls true
  - conda info -a

install:
    - conda create -n testenv -y -c conda-forge python=3.6
    - source activate testenv  
    - nslookup conda.anaconda.org
